### PR TITLE
Set http timeout to 30 mins. 

### PR DESCRIPTION
**Pull request by rc1**
By default aws only allows the http request 2 minutes to upload. This PR increases the limit to 30 minutes. It will also report when a request is being retried and including the reason why.

I was trying to upload 8megs at home. It was taking 8 minutes to report a fail. This was because it uploads for 2 mins, waiting for 1 min and attempts twice more.

Thanks.

### CODE REVIEW

**Comment by rc1** [comment]
It's just an arbitrary number. There is no limit from amazon.

I'm not sure what the additional tests would be? This PR is not expositing any additional functionality.

**Comment by DeviaVir** [comment]
@rc1 I was thinking about two tests, one to see if `aws.config.httpOptions.timeout` is being set (correctly), and one that would test the `retry` functionality you've added.

**Comment by rc1** [comment]
To clarify, I've not added the retry functionality. It's doing that already. I'm am just logging the event to report it's doing it to the console.

Being honest, I was just playing with a couple of free hours at home. I'd love to dig into the testing and figure it out... but I won't have time it the moment. Feel free to close.

**Comment by DeviaVir** [comment]
@rc1 apologies, it was not my intention to over-complicate things or to make this repo seem unreachable. I definitely want this change in as it makes `node-lambda` more usable for a broader public. Let me take a moment to see what kind of tests make sense and I'll be sure to add them on top of your changes.
Again, much appreciated that you spent some of your free time on this project.

**Comment by rc1** [comment]
@DeviaVir no apologies needed. It is a bit lame on my part.

Ingoring this PR, it would be helpful to have either `aws.config.httpOptions.timeout` changed or changeable.

**Pull request merged**
