### PR TITLE
Increase timeout in attempt to pass failing test on windows

### PR DESCRIPTION
**Pull request by motdotla**
Issue is a timeout test:

```
1) lib/main
       _packageInstall
         Use yarn
           should use "yarn install":
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\node-lambda\node-lambda\test\main.js)
      at listOnTimeout (node:internal/timers:573:17)
      at process.processTimers (node:internal/timers:514:7)
```

here: https://github.com/motdotla/node-lambda/blob/master/test/main.js#L823

### CODE REVIEW

**Review by abetomo — APPROVED** [review]
👍

**Comment by motdotla** [comment]
@abetomo I can't get this solved. Any ideas?

**Comment by abetomo** [comment]
Often times times out on Windows and Mac.
You may want to double it to 240,000 ms with the following settings.https://github.com/motdotla/node-lambda/blob/4e57052e0a4d92d1ae7993c79fdfab9721215c7b/test/main.js#L135-L139

**Comment by abetomo** [comment]
I will try to speed up the test, which is slow.

**Comment by abetomo** [comment]
Speed up testing #679

**Pull request closed without merging**
