### PR TITLE
Fix to display return value of handler

### LINKED ISSUE #426: node 8.10 async dosen't working
When I run this code:

```
const AWS = require('aws-sdk')
const s3 = new AWS.S3()

exports.handler = async function(event) {
  const operation = event.operation
  let expire = null

  // Set expiration
  if (event.expires && event.expires > 600) {
    expire = 300
  } else if (event.expires && event.expires < 600) {
    expire = event.expires
  } else {
    expire = 300
  }

  const params = {
    Bucket: event.bucket,
    Key: event.key,
    Metadata: event.metadata,
    Expires: expire,
    ContentType: event.contentType,
  }

  // Create URL
  const url = s3.getSignedUrl(operation, params)

  return url
}
```

I god no output in the terminal (when i run the same code with callback it works), when i set a console.log('xyz') a see the log on the console but the returnes value is not showed.

I use node8.10 as runtime and i have setted the runtime also in the .env file.

### PR DESCRIPTION
**Pull request by abetomo**
fixes #426

### CODE REVIEW

**Comment by phmiller** [comment]
I don't think this code works well for async handlers. Async handlers will return a promise which needs to be resolved before being pretty printed. I am using the following code, which coerce's non-promise values into resolved promises and resolves promise values before printing the result:

```javascript
 if (result != null) {
        Promise.resolve(result).then(resolved => {
            console.log("Result:");
            console.log(JSON.stringify(resolved));
        });
```

**Comment by abetomo** [comment]
@phmiller Thanks for the report!
My change was a bug.

Could you please PR?
I can also fix it.

**Comment by phmiller** [comment]
OK. So create a new PR with my code change? I can do that in the next few days

**Comment by phmiller** [comment]
Created https://github.com/motdotla/node-lambda/pull/440 for this change

**Pull request merged**
