### PR TITLE
Add changelog, and bump version

### PR DESCRIPTION
**Pull request by motdotla**

### CODE REVIEW

**Comment by DeviaVir** [comment]
Let's get this bumped up and deployed when the below list of PR's is merged?

- https://github.com/motdotla/node-lambda/pull/68
- https://github.com/motdotla/node-lambda/pull/56
- https://github.com/motdotla/node-lambda/pull/54
- https://github.com/motdotla/node-lambda/pull/51
- https://github.com/motdotla/node-lambda/pull/48
- https://github.com/motdotla/node-lambda/pull/40

I think that would make a great `0.0.8` release.

**Comment by DeviaVir** [comment]
@motdotla I'm running a few tests on current master and will then contact you to get `0.8.0` pushed out. We may also want to discuss the mentioned solution to semantic releases in brought up in https://github.com/motdotla/node-lambda/pull/39#issuecomment-211072939

**Comment by DeviaVir** [comment]
✅ Tests:

```
~ node-lambda/bin/node-lambda deploy -e staging -r us-west-2 -n test --handler index.handler -o arn:aws:iam::xxxxxxxxxxxx:role/lambda_basic_vpc_execution -d RemoveMe -u nodejs4.3 -p -b subnet-xxxxxxxx,subnet-xxxxxxxx -g sg-xxxxxxxx
Warning!!! You are building on a platform that is not 64-bit Linux (darwin.x64). If any of your Node dependencies include C-extensions, they may not work as expected in the Lambda environment.


=> Moving files to temporary directory
=> Running npm install --production
=> Zipping deployment package
=> Reading zip file to memory
=> Uploading zip file to AWS Lambda us-west-2 with parameters:
{ FunctionName: 'test-staging',
  Code: { ZipFile: <Buffer 50 4b 03 04 14 00 00 00 08 00 b6 65 92 48 6a 00 88 6d b2 00 00 00 04 18 00 00 09 00 1c 00 2e 44 53 5f 53 74 6f 72 65 55 54 09 00 03 d7 ba 14 57 d7 ba ... > },
  Handler: 'index.handler',
  Role: 'arn:aws:iam::xxxxxxxxxxxx:role/lambda_basic_vpc_execution',
  Runtime: 'nodejs4.3',
  Description: 'RemoveMe',
  MemorySize: '128',
  Timeout: '3',
  Publish: true,
  VpcConfig:
   { SubnetIds: [ 'subnet-xxxxxxxx', 'subnet-xxxxxxxx' ],
     SecurityGroupIds: [ 'sg-xxxxxxxx' ] } }
=> Zip file(s) done uploading. Results follow:
[ { FunctionName: 'test-staging',
    FunctionArn: 'arn:aws:lambda:us-west-2:xxxxxxxxxxxx:function:test-staging',
    Runtime: 'nodejs4.3',
    Role: 'arn:aws:iam::xxxxxxxxxxx:role/lambda_basic_vpc_execution',
    Handler: 'index.handler',
    CodeSize: 45021,
    Description: 'RemoveMe',
    Timeout: 3,
    MemorySize: 128,
    LastModified: '2016-04-18T10:45:45.422+0000',
    CodeSha256: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    Version: '1',
    VpcConfig:
     { SubnetIds: [Object],
       SecurityGroupIds: [Object],
       VpcId: 'vpc-xxxxxxxx' } } ]
```

**Comment by motdotla** [comment]
Huge thanks to @DeviaVir for tackling all these issues and putting things together! And thanks to all who submitted PR requests.

**Comment by motdotla** [comment]
semantic-release looks cool but I think overkill right now. We'll tag and release like normal.

**Pull request merged**
