### PR TITLE
Feature/event file

### PR DESCRIPTION
**Pull request by duckworth**
adds parameter -j --eventFile to the run command for testing alternate events. bumps version.

### CODE REVIEW

**Comment by motdotla** [comment]
Thanks for this @duckworth. Looks good but before I merge can you please update the README to reflect the new flag as well?

**Comment by duckworth** [comment]
Sure, @motdotla the README has been updated.

**Comment by motdotla** [comment]
:+1:

**Comment by motdotla** [comment]
Just published to npm. Thanks again @duckworth

**Pull request merged**
