### PR TITLE
Post install script environment

### PR DESCRIPTION
**Pull request by navihtot**
Passing environment string to post install script -> can be used to replace some config file depending on environment

### CODE REVIEW

**Comment by DeviaVir** [comment]
I would like to see a test for this, but noticed that `postInstall` has no tests at all yet so don't blame you for not creating them. +1, but keeping open for visibility to create tests later.

**Comment by navihtot** [comment]
Well to be honest I did introduce this feature in the first place, so I am the one to blame :blush: 
Will write tests when i find time :angel:

**Comment by navihtot** [comment]
There, this should be enough. Didn't find any nicer way to capture console output in node. :unamused:

**Comment by DeviaVir** [comment]
This is now available on NPM v0.8.10

**Comment by navihtot** [comment]
great, thanks!

**Pull request merged**
