### PR TITLE
Fix version of Node.js supported by AWS Lambda

### PR DESCRIPTION
**Pull request by abetomo**
https://aws.amazon.com/jp/about-aws/whats-new/2017/03/aws-lambda-supports-node-js-6-10/
http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html

### CODE REVIEW

**Comment by abetomo** [comment]
Thank you.
I fixed it, is there a problem?

**Comment by abetomo** [comment]
Failure of the test seems to be irrelevant to this fix, so we fixed it in a different branch
https://github.com/motdotla/node-lambda/pull/198

**Comment by bluepeter** [comment]
Hmm.. @abetomo I still get problems when deploying... Lambda returns node4.3...
```
{ FunctionName: 'XXX',
  Code: { ZipFile: <Buffer 50 4b 03 04 14 00 00 00 08 00 92 6d 78 4a 7f 0e da 58 05 01 00 00 53 01 00 00 04 00 1c 00 2e 65 6e 76 55 54 09 00 03 43 b2 d4 58 43 b2 d4 58 75 78 0b ... > },
  Handler: 'index.handler',
  Role: 'arn:aws:iam::XXX',
  Runtime: 'nodejs6.10',
  Description: 'XXX',
  MemorySize: '1024',
  Timeout: '60',
  Publish: false,
  VpcConfig: { SubnetIds: [], SecurityGroupIds: [] },
  Environment: { Variables: {} } }
=> Zip file(s) done uploading. Results follow:
[ { FunctionName: 'XXX',
    FunctionArn: 'arn:aws:lambda:us-east-1:XXXl',
    Runtime: 'nodejs4.3',
    Role: 'arn:aws:iam::XXX',
    Handler: 'index.handler',
    CodeSize: 27902661,
    Description: 'XXX',
    Timeout: 60,
    MemorySize: 1024,
    LastModified: '2017-03-24T05:45:09.137+0000',
    CodeSha256: 'XXX=',
    Version: '$LATEST',
    VpcConfig: { SubnetIds: [], SecurityGroupIds: [], VpcId: '' },
    KMSKeyArn: null } ]```

**Comment by abetomo** [comment]
@bluepeter
Are you deploying to the function already created with nodejs4.3?

In that case it will not be nodejs6.10 unless the https://github.com/motdotla/node-lambda/pull/200 fix is also included.

**Comment by bluepeter** [comment]
@abetomo yeah, that's the problem. Do you know if in #200 the update will update across, e.g., all versions/aliases of the function, or only in the `$latest` version?

**Comment by bluepeter** [comment]
(It appears it will just update `$latest`: "If you are using the versioning feature, note this API will always update the $LATEST version of your Lambda function.")

**Comment by abetomo** [comment]
Thank you. The idea was not extended to `version`.
As you pointed out, it seems that only `$latest` will be updated.

**Comment by DeviaVir** [comment]
This change is now live and published to NPM as `0.8.14`.

**Pull request merged**
