### PR TITLE
Removed event_sources.json

### PR DESCRIPTION
**Pull request by abetomo**
* Removed event_sources.json of the project root（The same file is in lib.）
* Removed unneeded space in lib/main.js

### CODE REVIEW

**Comment by limenutt** [comment]
@abetomo  I think this change has lead to the following error during deployment using 0.8.14
*Error: ENOENT: no such file or directory, open 'event_sources.json'*
```
at Error (native)
at Object.fs.openSync (fs.js:549:18)
at Object.fs.readFileSync (fs.js:397:15)
at Object.readFileSync (/tmp/src129258341/src/node_modules/node-lambda/node_modules/fs-extra/node_modules/jsonfile/index.js:66:20)
at Lambda._eventSourceList (/tmp/src129258341/src/node_modules/node-lambda/lib/main.js:141:28)
at /tmp/src129258341/src/node_modules/node-lambda/lib/main.js:561:33
at /tmp/src129258341/src/node_modules/node-lambda/lib/main.js:273:5
```

**Comment by abetomo** [comment]
@limenutt Have you run ‛node-lambda setup‛?

**Comment by abetomo** [comment]
`event_sources.json` is a file to be installed in the project root of each user.
(It will also be created in `node-lambda setup`)

That is, it is unnecessary for root of the `node-lambda` project.

**Comment by limenutt** [comment]
No I haven't run `node_lambda setup` with the new version. What happened is that one of my ci tasks failed to build and deploy lambda function because new version has been published with the change. I think that if I understand semver correctly, you should have incremented the minor version of the package with this update, since it could be a breaking change. Path version updates are reserved for bugfixes only.

**Comment by abetomo** [comment]
I was troubled with the same trouble so I tried opening the following PR.
https://github.com/motdotla/node-lambda/pull/205

**Pull request merged**
