### PR TITLE
Add '-x' / '--excludeGlobs' args for general file exclusion on deploy.

### LINKED ISSUE #32: Deployed zip contains temporary files .swp
Is there any way to exclude them?

### LINKED ISSUE #44: make exclude files config external
Currently we need to edit  ./lib/main.js to exclude the file we don't want to deploy.

can you make it works like .gitignore?
when first creating a aws-lambda project, run ```node-lambda init```, it will create a .xxignore file, so that we can exclude the files we don't want to deploy. 

thank you :)

### PR DESCRIPTION
**Pull request by rafalyesware**
This lets me e.g. exclude not only `.env` but by `.env.prod` / `.env.dev`
and any other junky / sample files that happen to live in the method's
directory.  Or for that matter to move all those files into a sub-
directory and exclude that.  Less policy, more flexibility.

Fixes #44 and fixes #32

### CODE REVIEW

**Comment by motdotla** [comment]
Thanks for this @rafalyesware. I'll take a look this weekend.

**Comment by rafalyesware** [comment]
Been a few weeks since that weekend; merged up to current master in case it helps @motdotla

**Comment by DeviaVir** [comment]
@rafalyesware if we can get https://github.com/rafalyesware/node-lambda/issues/1 merged into your branch, I'd like to get this merged! Adds great functionality.

**Comment by rafalyesware** [comment]
Thanks, I'll see what I can do this weekend.

--rafal

**Comment by DeviaVir** [comment]
As a general point, #40 already wanted to use `-x` so this might be something we'd have to take a look at to see which makes more sense.

**Comment by DeviaVir** [comment]
@rafalyesware did you get a chance to take a look already? I have been keeping the PR up to date with the changes to master.

**Comment by DeviaVir** [comment]
Deprecated by: https://github.com/motdotla/node-lambda/pull/80

**Pull request closed without merging**
